/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.motorph_1;


import java.awt.Color;
import javax.swing.JPanel;

/**
 *
 * @author AMD PC
 */
public class Homepage extends javax.swing.JFrame {

    /**
     * Creates new form Homepage
     */
    public Homepage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainpanel = new javax.swing.JPanel();
        headercontrol = new javax.swing.JPanel();
        headerbody = new javax.swing.JPanel();
        control = new javax.swing.JPanel();
        profilepic = new javax.swing.JButton();
        firstname = new javax.swing.JLabel();
        position = new javax.swing.JLabel();
        lastname = new javax.swing.JLabel();
        bthome = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        btpersinfo = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        bttime = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        btmypay = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        btcareer = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        btset = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        btpayroll = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        btlogout = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        pages = new javax.swing.JPanel();
        hmpage = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        infopage = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        timepage = new javax.swing.JPanel();
        paypage = new javax.swing.JPanel();
        workpage = new javax.swing.JPanel();
        payminpage = new javax.swing.JPanel();
        btPay1 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        dPay2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        dPay3 = new javax.swing.JPanel();
        dPay1 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        btPay2 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        btPay3 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        btPay4 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        btPay5 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        btPay6 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        payminpage3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jLabel23 = new javax.swing.JLabel();
        jFormattedTextField2 = new javax.swing.JFormattedTextField();
        jLabel24 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTextField1 = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mainpanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        headercontrol.setBackground(new java.awt.Color(140, 197, 255));
        headercontrol.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        mainpanel.add(headercontrol, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 170, 40));

        headerbody.setBackground(new java.awt.Color(104, 179, 255));
        headerbody.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        mainpanel.add(headerbody, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 0, 750, 40));

        control.setBackground(new java.awt.Color(255, 255, 255));
        control.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        profilepic.setIcon(new javax.swing.ImageIcon("D:\\Files\\Pictures\\Java Pics\\Profile pic icon upload.JPG")); // NOI18N
        profilepic.setBorder(javax.swing.BorderFactory.createCompoundBorder(null, javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, new java.awt.Color(0, 153, 255), java.awt.Color.darkGray, null, null)));
        control.add(profilepic, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 60, 60));

        firstname.setText("firstname");
        control.add(firstname, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, 70, -1));

        position.setText("position");
        control.add(position, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, 70, -1));

        lastname.setText("lastname");
        control.add(lastname, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, -1, -1));

        bthome.setBackground(new java.awt.Color(255, 255, 255));
        bthome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bthomeMouseClicked(evt);
            }
        });

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setIcon(new javax.swing.ImageIcon("D:\\Files\\Pictures\\Java Pics\\homepage icon.JPG")); // NOI18N

        javax.swing.GroupLayout bthomeLayout = new javax.swing.GroupLayout(bthome);
        bthome.setLayout(bthomeLayout);
        bthomeLayout.setHorizontalGroup(
            bthomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bthomeLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel10)
                .addContainerGap(58, Short.MAX_VALUE))
        );
        bthomeLayout.setVerticalGroup(
            bthomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bthomeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        control.add(bthome, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, -1, -1));

        btpersinfo.setBackground(new java.awt.Color(255, 255, 255));
        btpersinfo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btpersinfoMouseClicked(evt);
            }
        });

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon("D:\\Files\\Pictures\\Java Pics\\Personal Information icon.JPG")); // NOI18N

        javax.swing.GroupLayout btpersinfoLayout = new javax.swing.GroupLayout(btpersinfo);
        btpersinfo.setLayout(btpersinfoLayout);
        btpersinfoLayout.setHorizontalGroup(
            btpersinfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btpersinfoLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel3)
                .addContainerGap(58, Short.MAX_VALUE))
        );
        btpersinfoLayout.setVerticalGroup(
            btpersinfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btpersinfoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        control.add(btpersinfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, -1, 40));

        bttime.setBackground(new java.awt.Color(255, 255, 255));
        bttime.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bttimeMouseClicked(evt);
            }
        });

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setIcon(new javax.swing.ImageIcon("D:\\Files\\Pictures\\Java Pics\\time and attendance icone.JPG")); // NOI18N

        javax.swing.GroupLayout bttimeLayout = new javax.swing.GroupLayout(bttime);
        bttime.setLayout(bttimeLayout);
        bttimeLayout.setHorizontalGroup(
            bttimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bttimeLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel4)
                .addContainerGap(58, Short.MAX_VALUE))
        );
        bttimeLayout.setVerticalGroup(
            bttimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bttimeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        control.add(bttime, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, -1, 40));

        btmypay.setBackground(new java.awt.Color(255, 255, 255));
        btmypay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btmypayMouseClicked(evt);
            }
        });

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setIcon(new javax.swing.ImageIcon("D:\\Files\\Pictures\\Java Pics\\my pay icon.JPG")); // NOI18N

        javax.swing.GroupLayout btmypayLayout = new javax.swing.GroupLayout(btmypay);
        btmypay.setLayout(btmypayLayout);
        btmypayLayout.setHorizontalGroup(
            btmypayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btmypayLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel5)
                .addContainerGap(58, Short.MAX_VALUE))
        );
        btmypayLayout.setVerticalGroup(
            btmypayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btmypayLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        control.add(btmypay, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, -1, 40));

        btcareer.setBackground(new java.awt.Color(255, 255, 255));
        btcareer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btcareerMouseClicked(evt);
            }
        });

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setIcon(new javax.swing.ImageIcon("D:\\Files\\Pictures\\Java Pics\\career & workplace icon.JPG")); // NOI18N

        javax.swing.GroupLayout btcareerLayout = new javax.swing.GroupLayout(btcareer);
        btcareer.setLayout(btcareerLayout);
        btcareerLayout.setHorizontalGroup(
            btcareerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btcareerLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel6)
                .addContainerGap(58, Short.MAX_VALUE))
        );
        btcareerLayout.setVerticalGroup(
            btcareerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btcareerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        control.add(btcareer, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, -1, 40));

        btset.setBackground(new java.awt.Color(255, 255, 255));
        btset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btsetMouseClicked(evt);
            }
        });

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setIcon(new javax.swing.ImageIcon("D:\\Files\\Pictures\\Java Pics\\settings icon.JPG")); // NOI18N

        javax.swing.GroupLayout btsetLayout = new javax.swing.GroupLayout(btset);
        btset.setLayout(btsetLayout);
        btsetLayout.setHorizontalGroup(
            btsetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btsetLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel7)
                .addContainerGap(58, Short.MAX_VALUE))
        );
        btsetLayout.setVerticalGroup(
            btsetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btsetLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        control.add(btset, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, -1, 40));

        btpayroll.setBackground(new java.awt.Color(255, 255, 255));
        btpayroll.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btpayrollMouseClicked(evt);
            }
        });

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setIcon(new javax.swing.ImageIcon("D:\\Files\\Pictures\\Java Pics\\payrolladministration icon.JPG")); // NOI18N

        javax.swing.GroupLayout btpayrollLayout = new javax.swing.GroupLayout(btpayroll);
        btpayroll.setLayout(btpayrollLayout);
        btpayrollLayout.setHorizontalGroup(
            btpayrollLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btpayrollLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel8)
                .addContainerGap(58, Short.MAX_VALUE))
        );
        btpayrollLayout.setVerticalGroup(
            btpayrollLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btpayrollLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        control.add(btpayroll, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, -1, 40));

        btlogout.setBackground(new java.awt.Color(255, 255, 255));

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setIcon(new javax.swing.ImageIcon("D:\\Files\\Pictures\\Java Pics\\logout icon.JPG")); // NOI18N
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout btlogoutLayout = new javax.swing.GroupLayout(btlogout);
        btlogout.setLayout(btlogoutLayout);
        btlogoutLayout.setHorizontalGroup(
            btlogoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btlogoutLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel9)
                .addContainerGap(58, Short.MAX_VALUE))
        );
        btlogoutLayout.setVerticalGroup(
            btlogoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btlogoutLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        control.add(btlogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 450, -1, 40));

        mainpanel.add(control, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 160, 490));

        pages.setLayout(new java.awt.CardLayout());

        jLabel21.setText("welcome");

        javax.swing.GroupLayout hmpageLayout = new javax.swing.GroupLayout(hmpage);
        hmpage.setLayout(hmpageLayout);
        hmpageLayout.setHorizontalGroup(
            hmpageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hmpageLayout.createSequentialGroup()
                .addGap(238, 238, 238)
                .addComponent(jLabel21)
                .addContainerGap(464, Short.MAX_VALUE))
        );
        hmpageLayout.setVerticalGroup(
            hmpageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hmpageLayout.createSequentialGroup()
                .addGap(208, 208, 208)
                .addComponent(jLabel21)
                .addContainerGap(266, Short.MAX_VALUE))
        );

        pages.add(hmpage, "card2");

        jLabel1.setText("info");

        javax.swing.GroupLayout infopageLayout = new javax.swing.GroupLayout(infopage);
        infopage.setLayout(infopageLayout);
        infopageLayout.setHorizontalGroup(
            infopageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(infopageLayout.createSequentialGroup()
                .addGap(241, 241, 241)
                .addComponent(jLabel1)
                .addContainerGap(488, Short.MAX_VALUE))
        );
        infopageLayout.setVerticalGroup(
            infopageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(infopageLayout.createSequentialGroup()
                .addGap(131, 131, 131)
                .addComponent(jLabel1)
                .addContainerGap(343, Short.MAX_VALUE))
        );

        pages.add(infopage, "card3");

        javax.swing.GroupLayout timepageLayout = new javax.swing.GroupLayout(timepage);
        timepage.setLayout(timepageLayout);
        timepageLayout.setHorizontalGroup(
            timepageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 750, Short.MAX_VALUE)
        );
        timepageLayout.setVerticalGroup(
            timepageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 490, Short.MAX_VALUE)
        );

        pages.add(timepage, "card4");

        javax.swing.GroupLayout paypageLayout = new javax.swing.GroupLayout(paypage);
        paypage.setLayout(paypageLayout);
        paypageLayout.setHorizontalGroup(
            paypageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 750, Short.MAX_VALUE)
        );
        paypageLayout.setVerticalGroup(
            paypageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 490, Short.MAX_VALUE)
        );

        pages.add(paypage, "card5");

        javax.swing.GroupLayout workpageLayout = new javax.swing.GroupLayout(workpage);
        workpage.setLayout(workpageLayout);
        workpageLayout.setHorizontalGroup(
            workpageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 750, Short.MAX_VALUE)
        );
        workpageLayout.setVerticalGroup(
            workpageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 490, Short.MAX_VALUE)
        );

        pages.add(workpage, "card6");

        payminpage.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btPay1.setBackground(new java.awt.Color(255, 255, 255));
        btPay1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel19.setIcon(new javax.swing.ImageIcon("D:\\Files\\Pictures\\Java Pics\\icon8.JPG")); // NOI18N

        javax.swing.GroupLayout btPay1Layout = new javax.swing.GroupLayout(btPay1);
        btPay1.setLayout(btPay1Layout);
        btPay1Layout.setHorizontalGroup(
            btPay1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btPay1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel19)
                .addContainerGap(42, Short.MAX_VALUE))
        );
        btPay1Layout.setVerticalGroup(
            btPay1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btPay1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel19)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        payminpage.add(btPay1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 130, 70));

        dPay2.setBackground(new java.awt.Color(255, 255, 255));
        dPay2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel2.setIcon(new javax.swing.ImageIcon("D:\\Files\\Pictures\\Java Pics\\icon2.JPG")); // NOI18N

        jLabel20.setIcon(new javax.swing.ImageIcon("D:\\Files\\Pictures\\Java Pics\\icon9.JPG")); // NOI18N

        javax.swing.GroupLayout dPay2Layout = new javax.swing.GroupLayout(dPay2);
        dPay2.setLayout(dPay2Layout);
        dPay2Layout.setHorizontalGroup(
            dPay2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dPay2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dPay2Layout.createSequentialGroup()
                .addGap(0, 2, Short.MAX_VALUE)
                .addComponent(jLabel20))
        );
        dPay2Layout.setVerticalGroup(
            dPay2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dPay2Layout.createSequentialGroup()
                .addComponent(jLabel20)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addContainerGap())
        );

        payminpage.add(dPay2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, 130, 70));

        dPay3.setBackground(new java.awt.Color(255, 255, 255));
        dPay3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout dPay3Layout = new javax.swing.GroupLayout(dPay3);
        dPay3.setLayout(dPay3Layout);
        dPay3Layout.setHorizontalGroup(
            dPay3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 126, Short.MAX_VALUE)
        );
        dPay3Layout.setVerticalGroup(
            dPay3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 66, Short.MAX_VALUE)
        );

        payminpage.add(dPay3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 20, 130, 70));

        dPay1.setBackground(new java.awt.Color(255, 255, 255));
        dPay1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel11.setIcon(new javax.swing.ImageIcon("D:\\Files\\Pictures\\Java Pics\\icon1.JPG")); // NOI18N

        jLabel12.setIcon(new javax.swing.ImageIcon("D:\\Files\\Pictures\\Java Pics\\text1.JPG")); // NOI18N

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel13.setText("EEno");

        javax.swing.GroupLayout dPay1Layout = new javax.swing.GroupLayout(dPay1);
        dPay1.setLayout(dPay1Layout);
        dPay1Layout.setHorizontalGroup(
            dPay1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dPay1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dPay1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dPay1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel11))
                    .addGroup(dPay1Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        dPay1Layout.setVerticalGroup(
            dPay1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dPay1Layout.createSequentialGroup()
                .addComponent(jLabel12)
                .addGroup(dPay1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dPay1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jLabel11))
                    .addGroup(dPay1Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        payminpage.add(dPay1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 130, 70));

        btPay2.setBackground(new java.awt.Color(255, 255, 255));
        btPay2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel14.setIcon(new javax.swing.ImageIcon("D:\\Files\\Pictures\\Java Pics\\icon3.JPG")); // NOI18N

        javax.swing.GroupLayout btPay2Layout = new javax.swing.GroupLayout(btPay2);
        btPay2.setLayout(btPay2Layout);
        btPay2Layout.setHorizontalGroup(
            btPay2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btPay2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel14)
                .addContainerGap(27, Short.MAX_VALUE))
        );
        btPay2Layout.setVerticalGroup(
            btPay2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btPay2Layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addComponent(jLabel14)
                .addGap(20, 20, 20))
        );

        payminpage.add(btPay2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 200, 130, 70));

        btPay3.setBackground(new java.awt.Color(255, 255, 255));
        btPay3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel16.setIcon(new javax.swing.ImageIcon("D:\\Files\\Pictures\\Java Pics\\icon7.JPG")); // NOI18N

        javax.swing.GroupLayout btPay3Layout = new javax.swing.GroupLayout(btPay3);
        btPay3.setLayout(btPay3Layout);
        btPay3Layout.setHorizontalGroup(
            btPay3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btPay3Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel16)
                .addContainerGap(30, Short.MAX_VALUE))
        );
        btPay3Layout.setVerticalGroup(
            btPay3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btPay3Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel16)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        payminpage.add(btPay3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 200, 130, 70));

        btPay4.setBackground(new java.awt.Color(255, 255, 255));
        btPay4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel15.setIcon(new javax.swing.ImageIcon("D:\\Files\\Pictures\\Java Pics\\icon6.JPG")); // NOI18N

        javax.swing.GroupLayout btPay4Layout = new javax.swing.GroupLayout(btPay4);
        btPay4.setLayout(btPay4Layout);
        btPay4Layout.setHorizontalGroup(
            btPay4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btPay4Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel15)
                .addContainerGap(33, Short.MAX_VALUE))
        );
        btPay4Layout.setVerticalGroup(
            btPay4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btPay4Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel15)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        payminpage.add(btPay4, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 200, 130, 70));

        btPay5.setBackground(new java.awt.Color(255, 255, 255));
        btPay5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel18.setIcon(new javax.swing.ImageIcon("D:\\Files\\Pictures\\Java Pics\\icon5.JPG")); // NOI18N

        javax.swing.GroupLayout btPay5Layout = new javax.swing.GroupLayout(btPay5);
        btPay5.setLayout(btPay5Layout);
        btPay5Layout.setHorizontalGroup(
            btPay5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btPay5Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel18)
                .addContainerGap(28, Short.MAX_VALUE))
        );
        btPay5Layout.setVerticalGroup(
            btPay5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btPay5Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel18)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        payminpage.add(btPay5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 130, 70));

        btPay6.setBackground(new java.awt.Color(255, 255, 255));
        btPay6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel17.setIcon(new javax.swing.ImageIcon("D:\\Files\\Pictures\\Java Pics\\icon4.JPG")); // NOI18N

        javax.swing.GroupLayout btPay6Layout = new javax.swing.GroupLayout(btPay6);
        btPay6.setLayout(btPay6Layout);
        btPay6Layout.setHorizontalGroup(
            btPay6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btPay6Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel17)
                .addContainerGap(25, Short.MAX_VALUE))
        );
        btPay6Layout.setVerticalGroup(
            btPay6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btPay6Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel17)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        payminpage.add(btPay6, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 290, 130, 70));

        jPanel11.setBackground(new java.awt.Color(255, 255, 255));
        jPanel11.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 126, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 66, Short.MAX_VALUE)
        );

        payminpage.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 290, 130, 70));

        jPanel12.setBackground(new java.awt.Color(255, 255, 255));
        jPanel12.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 126, Short.MAX_VALUE)
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 66, Short.MAX_VALUE)
        );

        payminpage.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 290, 130, 70));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 610, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        payminpage.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 610, 30));

        pages.add(payminpage, "card7");

        payminpage3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel22.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(102, 153, 255));
        jLabel22.setText("Payroll Run");

        jFormattedTextField1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("MM/dd/yyyy"))));

        jLabel23.setText("Start Date");

        jLabel24.setText("End Date");

        jButton1.setText("START");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel22)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel23)
                            .addComponent(jLabel24))
                        .addGap(34, 34, 34)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jFormattedTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
                            .addComponent(jFormattedTextField1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(jFormattedTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFormattedTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24)
                    .addComponent(jButton1))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        payminpage3.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 19, -1, -1));

        jTable1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Employee No", "Employee Name", "Basic", "Rice", "Phone", "Clothing", "Net Pay"
            }
        ));
        jTable1.setSelectionBackground(new java.awt.Color(204, 204, 204));
        jScrollPane1.setViewportView(jTable1);

        payminpage3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 690, 310));
        payminpage3.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 20, 120, -1));

        jLabel25.setText("Employee No.");
        payminpage3.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 20, -1, -1));

        jButton2.setText("View");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        payminpage3.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 20, -1, -1));

        pages.add(payminpage3, "card8");

        mainpanel.add(pages, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 40, 750, 490));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainpanel, javax.swing.GroupLayout.DEFAULT_SIZE, 914, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

 
    private void onclick(JPanel panel){
        panel.setBackground(new Color(140,197,255));
    }
    
    private void onmouseleave(JPanel panel){
        panel.setBackground(new Color(255,255,255));
    }
    private void bthomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bthomeMouseClicked
        // TODO add your handling code here:
        onclick(bthome);
        onmouseleave(btmypay);
        onmouseleave(btcareer);
        onmouseleave(btpayroll);
        onmouseleave(btpersinfo);
        onmouseleave(btset);
        onmouseleave(bttime);
        
        hmpage.setVisible(true);
        infopage.setVisible(false);
        timepage.setVisible(false);
        paypage.setVisible(false);
        workpage.setVisible(false);
    }//GEN-LAST:event_bthomeMouseClicked

    private void btpersinfoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btpersinfoMouseClicked
        // TODO add your handling code here:
        onmouseleave(bthome);
        onmouseleave(btmypay);
        onmouseleave(btcareer);
        onmouseleave(btpayroll);
        onclick(btpersinfo);
        onmouseleave(btset);
        onmouseleave(bttime);
        
        infopage.setVisible(true);
    }//GEN-LAST:event_btpersinfoMouseClicked

    private void bttimeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bttimeMouseClicked
        // TODO add your handling code here:
        onmouseleave(bthome);
        onmouseleave(btmypay);
        onmouseleave(btcareer);
        onmouseleave(btpayroll);
        onmouseleave(btpersinfo);
        onmouseleave(btset);
        onclick(bttime);
        
        timepage.setVisible(true);
    }//GEN-LAST:event_bttimeMouseClicked

    private void btmypayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btmypayMouseClicked
        // TODO add your handling code here:
        onmouseleave(bthome);
        onclick(btmypay);
        onmouseleave(btcareer);
        onmouseleave(btpayroll);
        onmouseleave(btpersinfo);
        onmouseleave(btset);
        onmouseleave(bttime);
        
        paypage.setVisible(true);
    }//GEN-LAST:event_btmypayMouseClicked

    private void btcareerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btcareerMouseClicked
        // TODO add your handling code here:
        onmouseleave(bthome);
        onmouseleave(btmypay);
        onclick(btcareer);
        onmouseleave(btpayroll);
        onmouseleave(btpersinfo);
        onmouseleave(btset);
        onmouseleave(bttime);
        
        workpage.setVisible(true);
    }//GEN-LAST:event_btcareerMouseClicked

    private void btsetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btsetMouseClicked
        // TODO add your handling code here:
        onmouseleave(bthome);
        onmouseleave(btmypay);
        onmouseleave(btcareer);
        onmouseleave(btpayroll);
        onmouseleave(btpersinfo);
        onclick(btset);
        onmouseleave(bttime);
        
        
    }//GEN-LAST:event_btsetMouseClicked

    private void btpayrollMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btpayrollMouseClicked
        // TODO add your handling code here:
        onmouseleave(bthome);
        onmouseleave(btmypay);
        onmouseleave(btcareer);
        onclick(btpayroll);
        onmouseleave(btpersinfo);
        onmouseleave(btset);
        onmouseleave(bttime);
        
        payminpage.setVisible(true);
          hmpage.setVisible(false);
        infopage.setVisible(false);
        timepage.setVisible(false);
        paypage.setVisible(false);
        workpage.setVisible(false);
        
    }//GEN-LAST:event_btpayrollMouseClicked

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        // TODO add your handling code here:
       
    }//GEN-LAST:event_jLabel9MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Homepage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btPay1;
    private javax.swing.JPanel btPay2;
    private javax.swing.JPanel btPay3;
    private javax.swing.JPanel btPay4;
    private javax.swing.JPanel btPay5;
    private javax.swing.JPanel btPay6;
    private javax.swing.JPanel btcareer;
    private javax.swing.JPanel bthome;
    private javax.swing.JPanel btlogout;
    private javax.swing.JPanel btmypay;
    private javax.swing.JPanel btpayroll;
    private javax.swing.JPanel btpersinfo;
    private javax.swing.JPanel btset;
    private javax.swing.JPanel bttime;
    private javax.swing.JPanel control;
    private javax.swing.JPanel dPay1;
    private javax.swing.JPanel dPay2;
    private javax.swing.JPanel dPay3;
    private javax.swing.JLabel firstname;
    private javax.swing.JPanel headerbody;
    private javax.swing.JPanel headercontrol;
    private javax.swing.JPanel hmpage;
    private javax.swing.JPanel infopage;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JFormattedTextField jFormattedTextField2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lastname;
    private javax.swing.JPanel mainpanel;
    private javax.swing.JPanel pages;
    private javax.swing.JPanel payminpage;
    private javax.swing.JPanel payminpage3;
    private javax.swing.JPanel paypage;
    private javax.swing.JLabel position;
    private javax.swing.JButton profilepic;
    private javax.swing.JPanel timepage;
    private javax.swing.JPanel workpage;
    // End of variables declaration//GEN-END:variables
}
